// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SystemServiceClient is the client API for SystemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SystemServiceClient interface {
	StreamSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (SystemService_StreamSystemsClient, error)
	GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*SystemResponse, error)
	CreateSystem(ctx context.Context, in *CreateSystemRequest, opts ...grpc.CallOption) (*CreateSystemResponse, error)
	UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*UpdateSystemResponse, error)
	DeleteSystem(ctx context.Context, in *DeleteSystemRequest, opts ...grpc.CallOption) (*DeleteSystemResponse, error)
}

type systemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSystemServiceClient(cc grpc.ClientConnInterface) SystemServiceClient {
	return &systemServiceClient{cc}
}

func (c *systemServiceClient) StreamSystems(ctx context.Context, in *GetSystemsRequest, opts ...grpc.CallOption) (SystemService_StreamSystemsClient, error) {
	stream, err := c.cc.NewStream(ctx, &SystemService_ServiceDesc.Streams[0], "/anchamber.genetics.SystemService/StreamSystems", opts...)
	if err != nil {
		return nil, err
	}
	x := &systemServiceStreamSystemsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SystemService_StreamSystemsClient interface {
	Recv() (*SystemResponse, error)
	grpc.ClientStream
}

type systemServiceStreamSystemsClient struct {
	grpc.ClientStream
}

func (x *systemServiceStreamSystemsClient) Recv() (*SystemResponse, error) {
	m := new(SystemResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *systemServiceClient) GetSystem(ctx context.Context, in *GetSystemRequest, opts ...grpc.CallOption) (*SystemResponse, error) {
	out := new(SystemResponse)
	err := c.cc.Invoke(ctx, "/anchamber.genetics.SystemService/GetSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) CreateSystem(ctx context.Context, in *CreateSystemRequest, opts ...grpc.CallOption) (*CreateSystemResponse, error) {
	out := new(CreateSystemResponse)
	err := c.cc.Invoke(ctx, "/anchamber.genetics.SystemService/CreateSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) UpdateSystem(ctx context.Context, in *UpdateSystemRequest, opts ...grpc.CallOption) (*UpdateSystemResponse, error) {
	out := new(UpdateSystemResponse)
	err := c.cc.Invoke(ctx, "/anchamber.genetics.SystemService/UpdateSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *systemServiceClient) DeleteSystem(ctx context.Context, in *DeleteSystemRequest, opts ...grpc.CallOption) (*DeleteSystemResponse, error) {
	out := new(DeleteSystemResponse)
	err := c.cc.Invoke(ctx, "/anchamber.genetics.SystemService/DeleteSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SystemServiceServer is the server API for SystemService service.
// All implementations must embed UnimplementedSystemServiceServer
// for forward compatibility
type SystemServiceServer interface {
	StreamSystems(*GetSystemsRequest, SystemService_StreamSystemsServer) error
	GetSystem(context.Context, *GetSystemRequest) (*SystemResponse, error)
	CreateSystem(context.Context, *CreateSystemRequest) (*CreateSystemResponse, error)
	UpdateSystem(context.Context, *UpdateSystemRequest) (*UpdateSystemResponse, error)
	DeleteSystem(context.Context, *DeleteSystemRequest) (*DeleteSystemResponse, error)
	mustEmbedUnimplementedSystemServiceServer()
}

// UnimplementedSystemServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSystemServiceServer struct {
}

func (UnimplementedSystemServiceServer) StreamSystems(*GetSystemsRequest, SystemService_StreamSystemsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamSystems not implemented")
}
func (UnimplementedSystemServiceServer) GetSystem(context.Context, *GetSystemRequest) (*SystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystem not implemented")
}
func (UnimplementedSystemServiceServer) CreateSystem(context.Context, *CreateSystemRequest) (*CreateSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSystem not implemented")
}
func (UnimplementedSystemServiceServer) UpdateSystem(context.Context, *UpdateSystemRequest) (*UpdateSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSystem not implemented")
}
func (UnimplementedSystemServiceServer) DeleteSystem(context.Context, *DeleteSystemRequest) (*DeleteSystemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSystem not implemented")
}
func (UnimplementedSystemServiceServer) mustEmbedUnimplementedSystemServiceServer() {}

// UnsafeSystemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SystemServiceServer will
// result in compilation errors.
type UnsafeSystemServiceServer interface {
	mustEmbedUnimplementedSystemServiceServer()
}

func RegisterSystemServiceServer(s grpc.ServiceRegistrar, srv SystemServiceServer) {
	s.RegisterService(&SystemService_ServiceDesc, srv)
}

func _SystemService_StreamSystems_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSystemsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SystemServiceServer).StreamSystems(m, &systemServiceStreamSystemsServer{stream})
}

type SystemService_StreamSystemsServer interface {
	Send(*SystemResponse) error
	grpc.ServerStream
}

type systemServiceStreamSystemsServer struct {
	grpc.ServerStream
}

func (x *systemServiceStreamSystemsServer) Send(m *SystemResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SystemService_GetSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).GetSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anchamber.genetics.SystemService/GetSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).GetSystem(ctx, req.(*GetSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_CreateSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).CreateSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anchamber.genetics.SystemService/CreateSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).CreateSystem(ctx, req.(*CreateSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_UpdateSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).UpdateSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anchamber.genetics.SystemService/UpdateSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).UpdateSystem(ctx, req.(*UpdateSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SystemService_DeleteSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SystemServiceServer).DeleteSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/anchamber.genetics.SystemService/DeleteSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SystemServiceServer).DeleteSystem(ctx, req.(*DeleteSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SystemService_ServiceDesc is the grpc.ServiceDesc for SystemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SystemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "anchamber.genetics.SystemService",
	HandlerType: (*SystemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSystem",
			Handler:    _SystemService_GetSystem_Handler,
		},
		{
			MethodName: "CreateSystem",
			Handler:    _SystemService_CreateSystem_Handler,
		},
		{
			MethodName: "UpdateSystem",
			Handler:    _SystemService_UpdateSystem_Handler,
		},
		{
			MethodName: "DeleteSystem",
			Handler:    _SystemService_DeleteSystem_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSystems",
			Handler:       _SystemService_StreamSystems_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "system.proto",
}
